add bash-scripting-guidelines.md
logiceditor-com/coding-guidelines pull request #24
Opened 2021-03-25 11:01 UTC by E-Fir

2021-03-25 11:15 UTC, agladysh requested changes

2021-03-25 11:15 UTC, agladysh commented on bash-scripting-guidelines.md
> +#! /usr/bin/env bash
нужно объяснить почему

2021-03-25 11:15 UTC, agladysh commented on bash-scripting-guidelines.md
> +
пропущено про set

2021-03-25 11:15 UTC, agladysh commented on bash-scripting-guidelines.md
> +All the variables must be in the lower case.
зачем артикль?

2021-03-25 11:15 UTC, agladysh commented on bash-scripting-guidelines.md
> +The use of variables is allowed only using `"${}"`.
непонятно, что это значит

2021-03-25 11:15 UTC, agladysh commented on bash-scripting-guidelines.md
> +
слишком сильное заявление про нижний регистр, на самом деле не так

2021-03-25 11:15 UTC, agladysh commented on bash-scripting-guidelines.md
> +If you need to use `"$@"`, always use quotation marks.
нужен пример

2021-03-25 11:15 UTC, agladysh commented on bash-scripting-guidelines.md
> +ROOT="${BASH_SOURCE[0]}"
О_О

потеряно три строки и весь смысл

2021-03-25 11:15 UTC, agladysh commented on bash-scripting-guidelines.md
> +exec /usr/bin/env ${LE_LUA_INTERPRETER} "$@"
нужно объяснить, зачем, и обратить внимание, что исполнение текущего скрипта прекратится

2021-04-01 09:11 UTC, E-Fir commented on bash-scripting-guidelines.md
> +#! /usr/bin/env bash
+

2021-04-01 09:11 UTC, E-Fir commented on bash-scripting-guidelines.md
> +
добавил раздел  Set options

2021-04-01 09:12 UTC, E-Fir commented on bash-scripting-guidelines.md
> +
Уточнил, что относится к локальным для скрипта переменным

2021-04-01 09:12 UTC, E-Fir commented on bash-scripting-guidelines.md
> +If you need to use `"$@"`, always use quotation marks.
добавил

2021-04-01 09:12 UTC, E-Fir commented on bash-scripting-guidelines.md
> +ROOT="${BASH_SOURCE[0]}"
добавил, было потеряно даже 4 строки

2021-04-01 09:13 UTC, E-Fir commented on bash-scripting-guidelines.md
> +All the variables must be in the lower case.
переписано

2021-04-01 09:13 UTC, E-Fir commented on bash-scripting-guidelines.md
> +The use of variables is allowed only using `"${}"`.
переписано

2021-04-01 09:13 UTC, E-Fir commented on bash-scripting-guidelines.md
> +exec /usr/bin/env ${LE_LUA_INTERPRETER} "$@"
добавил

2021-09-10 11:58 UTC, merged